language: csharp

solution: GenericMath.sln

sudo: required

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "n7eVJ6HYjK9T0H7uIQ4RkFyNP+koq2VpjGEpsR+lMzPFcBHr9MZR60Xoavzigx/rUWG8VXB/tH2t0M68pwfyWsq89ZzOlgP5kGPm6uY9GE7Ezm5XDBh+kgLWR5HJb6xrhz9yBWjRf55b6mTfrMP+1QTe+9xRcTEW9EgVlGi/KpvtG6a93RUuSJ5UTAO8ljcRjsXbfPduUH7VIVCLRawRtAhf/+w+gS/kz5JV6rMx9YssoS+77DMIp+FKGo9fAAlQTiAItKYwQNBG7XBDRAHR0R7BjmHdvvets66smY8gaM3lLTn+iIWtlYemnMFVC9w0p3b3rFEPOU5T7Do+7QxkJaqop2sLy0I/oSc5dweglRMqTMr6c6/5lwGwFZx/y0lnhB6BggVzc8SFjv17ZoEdfEpDdVzADrntTIjmRlEnjIdC0YGM3Bxmedv3eUWUmH1UDfVtZwiPg1TjrfU34OKvE5Eyz4ZWsn+niqn5y8q+UFT7IS+6T8pYaH0PcL1m7dmDuasJSa1DHPvA/8iVD61sxuqOS7oSxRCjW4zbKTKhdsqha08tF+14iXHwBJ3k5hueyARCF6dm8Y6ZbugLNQaId/GAwX0J20OAr5D/K31ssXWFcchAuVgqjy5MyRSewqN2yi09QC5+l+Y+ehp13RKS+kzOES2JQyvQpWDr2q82yWw="

before_install:
  - sudo apt-get install nunit-console

before_script:
  - nuget restore GenericMath.sln

after_script:
  - nunit-console Tests/GenericMath.Analysis.Tests/bin/Debug/GenericMath.Analysis.Tests.dll
  - nunit-console Tests/GenericMath.Base.Tests/bin/Debug/GenericMath.Base.Tests.dll
  - nunit-console Tests/GenericMath.Common.Tests/bin/Debug/GenericMath.Common.Tests.dll
  - nunit-console Tests/GenericMath.LinearAlgebra.Tests/bin/Debug/GenericMath.LinearAlgebra.Tests.dll
  - nunit-console Tests/GenericMath.Parser.Tests/bin/Debug/GenericMath.Parser.Tests.dll

script:
  - xbuild /p:Configuration=Debug GenericMath.sln

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  coverity_scan:
    project:
      name: "AndreasAugustin/testing-demos-csharp_mono"
      description: "Build submitted via Travis CI"
    notification_email: andy.augustin@t-online.de
    build_command_prepend: "msbuild /t:Clean"
    build_command:   "msbuild /t:Rebuild"
    branch_pattern: master

