language: csharp

solution: GenericMath.sln

sudo: required

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "h82fhgn0aSCb7f4mATIUcskEfbsOT4/0rxqoR/Bx112G1VO8CrQQICTYEBM1vj2KX4euduWS/vpY1SZtv/LiXysQML/K9gg5lGkA1JVO937PcJaQGS4Vo0tvQ2aOS2Fd5OmsydG/7G82qQsi9pJR4Vdd7KY6yH9VwWb1EdpqjlEOgcBh25+t4UeCQta2+cqRs3ayicc5FT2QmtHA/zNgtVPWiufp7iFOAAKhosJDjJZkt8ljg6rdctSrl/VuTfQN8pRczZ3tqK/Vj1/jnYgOSyhkRCVhnUKK+c83ZogHGU9CiopnCCt5au6fEJNGHhZ26h8rwgTxWPeqhgXjDfb1db2btJFLrIKc6wIWGR/v5D/eZbtu9S+AWcdW3qI7baQ9kuGK4iAUbhAwIzQbUE+uxS8dzfZCbjaua47rtd+FMcHPLLONswSzDakgZN9vHmu7nErcsLCsglzm2JYKnwk/nxa+7Xo5OLytQbHpnva/ijotpq5u2AvQBhKGY4MSERRIDHNv2vEOHDHYgdLqXMPyuZxgXDVeIOuhMCP/zUu7UgTujQVkYPL5u0d9seZNrSJCJVBmA5p2oo2RBfUpDYRHKCnfi6Gwp4Q0OY1ESDTtYgzTkoliH1CJRQGOxFW1wy/9DyYG9hJZp6allpGDg1d9fdzyk+7GiQG0WT8ii50/Z0M="


before_install:
  - sudo apt-get install nunit-console

before_script:
  - nuget restore GenericMath.sln

after_script:
  - nunit-console Tests/GenericMath.Analysis.Tests/bin/Debug/GenericMath.Analysis.Tests.dll
  - nunit-console Tests/GenericMath.Base.Tests/bin/Debug/GenericMath.Base.Tests.dll
  - nunit-console Tests/GenericMath.Common.Tests/bin/Debug/GenericMath.Common.Tests.dll
  - nunit-console Tests/GenericMath.LinearAlgebra.Tests/bin/Debug/GenericMath.LinearAlgebra.Tests.dll
  - nunit-console Tests/GenericMath.Parser.Tests/bin/Debug/GenericMath.Parser.Tests.dll

script:
  - xbuild /p:Configuration=Debug GenericMath.sln

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  coverity_scan:
    project:
      name: "AndreasAugustin/GenericMath"
      description: "Build submitted via Travis CI"
    notification_email: andy.augustin@t-online.de
    build_command_prepend: "msbuild /t:Clean"
    build_command:   "msbuild /t:Rebuild"
    branch_pattern: master

